[platformio]
default_envs = bedroom_remote

[env:bedroom_remote]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps =
    https://github.com/commputethis/waveshare-s3-touch.git
    symlink://../../libraries/HomeRemoteProtocol
build_flags =
    -std=gnu++17
    -DCORE_DEBUG_LEVEL=3
